# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MrManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'SwiftLint'
  # Pods for MrManager

  target 'MrManagerUseCaseTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxSwift'
    pod 'RxRelay'
  end

  target 'MrManagerViewModelTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxSwift'
    pod 'RxRelay'
  end

end
